In [1]:
import os
import pandas as pd
import numpy as np

data_dir = "../data"
file_paths = {
    "presentations_df": os.path.join(data_dir, "presentations_df.csv"),
    "user_profiles": os.path.join(data_dir, "user_profiles.csv"),
    "user_profiles_flat": os.path.join(data_dir, "user_profiles_flat.csv"),
    "recommendations": os.path.join(data_dir, "recommendations.csv"),
    "ratings_matrix": os.path.join(data_dir, "ratings_matrix.csv"),
    "interaction_data": os.path.join(data_dir, "interaction_data.csv"),
    "X": os.path.join(data_dir, "X.csv"),
    "y": os.path.join(data_dir, "y.csv"),
    "feature_columns": os.path.join(data_dir, "feature_columns.txt")
}

def safe_read_csv(path, name):
    if os.path.exists(path):
        return pd.read_csv(path)
    else:
        print(f"⚠️ File not found: {name} -> {path}")
        return None

# Load all CSVs
presentations_df = safe_read_csv(file_paths["presentations_df"], "presentations_df")
user_profiles = safe_read_csv(file_paths["user_profiles"], "user_profiles")
user_profiles_flat = safe_read_csv(file_paths["user_profiles_flat"], "user_profiles_flat")
recommendations = safe_read_csv(file_paths["recommendations"], "recommendations")
ratings_matrix = safe_read_csv(file_paths["ratings_matrix"], "ratings_matrix")
interaction_data = safe_read_csv(file_paths["interaction_data"], "interaction_data")

# Load X and y
X_df = safe_read_csv(file_paths["X"], "X")
X = X_df.values if X_df is not None else None

y_df = safe_read_csv(file_paths["y"], "y")
y = y_df.values.flatten() if y_df is not None else None

# Load feature columns
if os.path.exists(file_paths["feature_columns"]):
    with open(file_paths["feature_columns"], "r") as f:
        feature_columns = [line.strip() for line in f]
else:
    print(f"⚠️ File not found: feature_columns.txt -> {file_paths['feature_columns']}")
    feature_columns = None

In [10]:
# ###DATASET GENERATION
# import pandas as pd
# import numpy as np

# recommendations_for_user_id=1
# num_users = 50
# num_articles = 500

# # Generate articles dataset
# recommendations = create_dataset(num_articles)

# # Generate users:
# user_profiles = generate_user_profiles(num_users, types, locations, preferences_options)

# #Generate presentations
# presentations_df = generate_presentations_for_users(user_profiles, presentation_problems)

# #Generate rating matrix
# ratings_matrix = None
# ratings_matrix = generate_ratings_matrix(
#     user_profiles, recommendations, presentations_df, ratings_matrix
# )
# #print("Rating matrix len: "+str(len(ratings_matrix)))

# from sklearn.model_selection import train_test_split
# from sklearn.metrics import mean_squared_error

# # Step 0: Preprocess the user profile
# user_profiles_flat = preprocess_user_profile(user_profiles, preferences_options, types, presentation_type_options)

# # Step 2: Prepare interaction data
# interaction_data, X, y, feature_columns = prepare_interaction_data(user_profiles_flat, recommendations, ratings_matrix,presentation_type_options,audience_type_options)

C:\Users\maria\AppData\Local\Temp\ipykernel_10632\1901713504.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_presentations["recency_weight"] = (

Index(['user_id', 'article_id', 'rating', 'timestamp', 'location',
       'user_preference_Boring presentation', 'user_preference_Graphics',
       'user_preference_Readability', 'user_preference_Consistency',
       'user_preference_Images', 'user_preference_Bullets',
       'user_preference_Text size', 'user_preference_Text heavy',
       'user_preference_Tables', 'user_preference_Agenda',
       'user_preference_Infographics', 'user_preference_Positioning',
       'user_preference_Presentation length', 'user_preference_General tips',
       'user_preference_Presentation skills',
       'user_preference_Powerpoint knowledge',
       'user_preference_tips and tricks',
       'user_preference_Explanation of the problem', 'user_type_business',
       'user_type_teacher', 'user_type_student', 'user_type_researcher',
       'user_type_manager', 'user_type_technical', 'user_type_specialist',
       'presentation_type_formal_x', 'presentation_type_creative_x',
       'presentation_type_students_x', 'presentation_type_technical_x',
       'presentation_type_branding_x', 'Boring presentation', 'Graphics',
       'Readability', 'Consistency', 'Images', 'Bullets', 'Text size',
       'Text heavy', 'Tables', 'Agenda', 'Infographics', 'Positioning',
       'Presentation length', 'General tips', 'Presentation skills',
       'Powerpoint knowledge', 'tips and tricks', 'Explanation of the problem',
       'location_restrictions', 'Main issue', 'popularity',
       'presentation_type_formal_y', 'presentation_type_creative_y',
       'presentation_type_students_y', 'presentation_type_technical_y',
       'presentation_type_branding_y', 'audience_type_academic',
       'audience_type_business', 'audience_type_kids', 'audience_type_general',
       'audience_type_creative', 'audience_type_specialized'],
      dtype='object')

In [2]:
data1 = interaction_data.copy()

In [9]:
user_features_names=['user_preference_Boring presentation',
 'user_preference_Graphics',
 'user_preference_Readability',
 'user_preference_Consistency',
 'user_preference_Images',
 'user_preference_Bullets',
 'user_preference_Text size',
 'user_preference_Text heavy',
 'user_preference_Tables',
 'user_preference_Agenda',
 'user_preference_Infographics',
 'user_preference_Positioning',
 'user_preference_Presentation length',
 'user_preference_General tips',
 'user_preference_Presentation skills',
 'user_preference_Powerpoint knowledge',
 'user_preference_tips and tricks',
 'user_preference_Explanation of the problem',
 'user_type_business',
 'user_type_teacher',
 'user_type_student',
 'user_type_researcher',
 'user_type_manager',
 'user_type_technical',
 'user_type_specialist',
 'presentation_type_formal_x',
 'presentation_type_creative_x',
 'presentation_type_students_x',
 'presentation_type_technical_x',
 'presentation_type_branding_x']
item_features_names=[ 'Boring presentation',
 'Graphics',
 'Readability',
 'Consistency',
 'Images',
 'Bullets',
 'Text size',
 'Text heavy',
 'Tables',
 'Agenda',
 'Infographics',
 'Positioning',
 'Presentation length',
 'General tips',
 'Presentation skills',
 'Powerpoint knowledge',
 'tips and tricks',
 'Explanation of the problem',
 'presentation_type_formal_y',
 'presentation_type_creative_y',
 'presentation_type_students_y',
 'presentation_type_technical_y',
 'presentation_type_branding_y',
 'audience_type_academic',
 'audience_type_business',
 'audience_type_kids',
 'audience_type_general',
 'audience_type_creative',
 'audience_type_specialized']
data1.head(3)

,user_id,article_id,rating,timestamp,days_since_last_rating,location,user_preference_Boring presentation,user_preference_Graphics,user_preference_Readability,user_preference_Consistency,...,presentation_type_students_y,presentation_type_technical_y,presentation_type_branding_y,audience_type_academic,audience_type_business,audience_type_kids,audience_type_general,audience_type_creative,audience_type_specialized,time_since
0,1,1,4.5,2021-07-27 04:00:00+00:00,5717.16650,Illinois,0,0,0,0,...,0,0,0,0,0,0,0,0,0,33950.0
1,1,14,4.0,2006-09-07 04:00:00+00:00,280.16666,Illinois,0,0,0,0,...,0,0,0,0,0,0,0,0,0,164438.0
2,1,78,4.5,2013-08-01 13:00:00+00:00,2800.54170,Illinois,0,0,0,0,...,0,0,0,0,0,0,0,0,0,103949.0

In [5]:
# import pandas as pd

# # Convert timestamp to datetime format
# data1["timestamp"] = pd.to_datetime(data1["timestamp"])

# # Compute time_since in hours from the most recent timestamp
# max_timestamp = data1["timestamp"].max()
# data1["time_since"] = (max_timestamp - data1["timestamp"]).dt.total_seconds() / 3600

In [10]:
import numpy as np
import pandas as pd


interaction_data = interaction_data.sort_values(by=['user_id', 'article_id']).reset_index(drop=True)

def extract_time_features(dates, start_time):
    # Convert to datetime with UTC if not already
    df_temp = pd.DataFrame({'Datetime': pd.to_datetime(dates, errors='coerce')})

    # Ensure timezone awareness (UTC)
    if df_temp['Datetime'].dt.tz is None:
        df_temp['Datetime'] = df_temp['Datetime'].dt.tz_localize('UTC')
    else:
        df_temp['Datetime'] = df_temp['Datetime'].dt.tz_convert('UTC')

    # Ensure start_time is timezone-aware
    start_time = pd.to_datetime(start_time, utc=True)

    # Sort values
    df_temp = df_temp.sort_values(by='Datetime').reset_index(drop=True)

    # Extract cyclical time features
    df_temp['Hour'] = df_temp['Datetime'].dt.hour
    df_temp['Day_of_Week'] = df_temp['Datetime'].dt.dayofweek
    df_temp['Hour_sin'] = np.sin(2 * np.pi * df_temp['Hour'] / 24)
    df_temp['Hour_cos'] = np.cos(2 * np.pi * df_temp['Hour'] / 24)
    df_temp['Day_sin'] = np.sin(2 * np.pi * df_temp['Day_of_Week'] / 7)
    df_temp['Day_cos'] = np.cos(2 * np.pi * df_temp['Day_of_Week'] / 7)

    # Time since first submission in hours
    df_temp['Time_since_first_submission_hours'] = (
        (df_temp['Datetime'] - start_time).dt.total_seconds() / 3600
    ).astype(np.float32)

    return df_temp[['Hour_sin', 'Hour_cos', 'Day_sin', 'Day_cos', 'Time_since_first_submission_hours']]

# Ensure start_time is timezone-aware
start_time = pd.to_datetime("2005-12-01 00:00:00", utc=True)

# Apply time feature extraction to interaction and presentation data
time_features = extract_time_features(interaction_data['timestamp'], start_time)

user_features = interaction_data[user_features_names]
item_features = interaction_data[item_features_names]
X_user_id = interaction_data['user_id']
X_item_id = interaction_data['article_id']

# Problem features
problem_features = [
    'Boring presentation', 'Graphics', 'Readability', 'Consistency',
    'Images', 'Bullets', 'Text size', 'Text heavy', 'Tables',
    'Agenda', 'Infographics', 'Positioning'
]

# Process presentation features and timestamps
presentation_df_temp = presentations_df.sort_values(by='user_id').reset_index(drop=True)
presentation_submission_date_df = extract_time_features(presentation_df_temp['submission_date'], start_time)

# Concatenate user_id, problem features, and time features
problem_sequences_df = pd.concat(
    [presentations_df['user_id'], presentations_df[problem_features], presentation_submission_date_df],
    axis=1
)

y = interaction_data['rating']

In [11]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

def calculate_problem_weights(df, date_column, problem_columns, days_window=90, decay_factor=0.01, apply_filter=True):
    """
    Изчислява претеглена вероятност за всеки проблем на база на презентации от последните days_window дни.
    Важно: Колоната, зададена с date_column, съдържа време в часове от първата подадена презентация.
    :param df: DataFrame с колоните [date_column] и [problem_columns]
    :param date_column: Име на колоната, която съдържа времето (в часове) от първата submission.
    :param problem_columns: Списък с колоните за проблемите (0 или 1)
    :param days_window: Колко дни назад да се вземат презентации (по подразбиране 90 дни)
    :param decay_factor: Фактор на затихване (по подразбиране 0.01)
    :param apply_filter: Ако True, филтрира по времевия прозорец. Ако False, използва целия DataFrame.
    :return: df_filtered (или оригиналния df ако не се филтрира) и NumPy масив с претеглените стойности за всеки проблем.
    """
    
    # Ако DataFrame има само един ред, връщаме директно неговите стойности.
    if len(df) <= 1:
        arr = np.array([df[col].iloc[0] if not df.empty else 0 for col in problem_columns])
        return df, arr

    # Ако apply_filter е True, филтрираме редовете според времевия прозорец.
    # Изчисляваме прага в часове (дни_window * 24)
    if apply_filter:
        threshold_hours = days_window * 24
        df_filtered = df[df[date_column] <= threshold_hours]
    else:
        df_filtered = df.copy()

    # Ако след филтрирането няма редове, връщаме масив със 0 стойности.
    if df_filtered.empty:
        print("No data after filtering. Returning zeros.")
        return df, np.array([0 for _ in problem_columns])
    
    # Изчисляване на тежестите спрямо възрастта на презентациите.
    # Тъй като колоната е в часове, преобразуваме часовете в дни (делим на 24)
    # за да запазим decay_factor, дефиниран за дни.
    df_filtered["weight"] = np.exp(-decay_factor * (df_filtered[date_column] / 24))
    
    # Изчисляване на претегленото средно за всеки проблем
    weighted_problems = np.array([
        (df_filtered[col] * df_filtered["weight"]).sum() / df_filtered["weight"].sum() 
        for col in problem_columns
    ])
    
    return df_filtered, weighted_problems

padded_problem_sequences = []
user_data = {}

df_user_full = data1[user_features].copy()
for user_id_to_fetch in X_user_id:
    if user_id_to_fetch in user_data:
        # If user data is already calculated, use it directly
        weighted_problems = user_data[user_id_to_fetch]
    else:
        # Filter the DataFrame for the current user
        df_user = problem_sequences_df[problem_sequences_df['user_id'] == user_id_to_fetch]
        # Calculate weighted problems
        _, weighted_problems = calculate_problem_weights(df_user, 
                                                          "Time_since_first_submission_hours", 
                                                          problem_features, 
                                                          days_window=180, 
                                                          decay_factor=0.01, 
                                                          apply_filter=False)
        
        # Store the result in user_data
        user_data[user_id_to_fetch] = weighted_problems
        
    
    # Append to padded_problem_sequences
    padded_problem_sequences.append(weighted_problems)
    
padded_problem_sequences = np.array(padded_problem_sequences)
print(padded_problem_sequences.shape)
# If it's 1D  reshape to 2D Keras typically expects a 2D tensor for each input, where:The first dimension (axis 0) represents the number of samples in the batch.The second dimension (axis 1) represents the features for each sample.
#if len(padded_problem_sequences.shape) == 1:
#    padded_problem_sequences = padded_problem_sequences.reshape(-1, 1)

df_new = pd.DataFrame(padded_problem_sequences, columns=problem_features)
df_user_full = pd.concat([df_user_full, df_new], axis=1)

ValueError: Boolean array expected for the condition, not int64

In [7]:
user_features_full = df_user_full.copy()  # Copy to avoid modifying original
columns_to_rename = ['Boring presentation', 'Graphics', 'Readability', 'Consistency', 
                     'Images', 'Bullets', 'Text size', 'Text heavy', 'Tables', 
                     'Agenda', 'Infographics', 'Positioning']

user_features_full = user_features_full.rename(columns={col: f"user_presentation_problem_{col}" for col in columns_to_rename})

item_features_full = data1[item_features].copy()  # Copy item features
merged_features = pd.concat([user_features_full, data1[item_features], data1[['rating','popularity', 'user_id','article_id']]], axis=1)
merged_features.columns

NameError: name 'df_user_full' is not defined

In [36]:
from sklearn.model_selection import train_test_split

# Step 1: Extract user & item features from the full dataset
user_features_full = df_user_full.copy()  # Copy to avoid modifying original
item_features_full = data1[item_features].copy()  # Copy item features


# Step 2: First split: 70% Train, 30% Temporary (Val + Test)
train_data, temp_data = train_test_split(data1, test_size=0.30, random_state=42)

# Step 3: Second split: 50% of temp_data goes to Val, 50% to Test (15% each)
val_data, test_data = train_test_split(temp_data, test_size=0.50, random_state=42)

# Step 4: Match user and item features for each split
train_user_features = user_features_full.loc[train_data.index]
train_item_features = item_features_full.loc[train_data.index]
train_target = y.loc[train_data.index]

val_user_features = user_features_full.loc[val_data.index]
val_item_features = item_features_full.loc[val_data.index]
val_target = y.loc[val_data.index]

test_user_features = user_features_full.loc[test_data.index]
test_item_features = item_features_full.loc[test_data.index]
test_target = y.loc[test_data.index]


# Print data sizes to verify correct splitting
print(f"Train Data: {len(train_data)} rows")
print(f"Validation Data: {len(val_data)} rows")
print(f"Test Data: {len(test_data)} rows")

# Example usage
print("y:", len(y))  # Ensure y also has 25,000 elements

Train Data: 17500 rows
Validation Data: 3750 rows
Test Data: 3750 rows
y: 25000

In [31]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: joblib>=1.2.0 in c:\users\maria\anaconda3\envs\dev_env\lib\site-packages (from scikit-surprise) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\maria\anaconda3\envs\dev_env\lib\site-packages (from scikit-surprise) (1.19.5)
Requirement already satisfied: scipy>=1.6.0 in c:\users\maria\anaconda3\envs\dev_env\lib\site-packages (from scikit-surprise) (1.10.1)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml): started
  Building wheel for scikit-surprise (pyproject.toml): finished with status 'done'
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp38-cp38-win_amd64.whl size=1292723 sha256=2c134c7ba6dcbfcd5f6ec7012eba92f00c091cf80a7cc7ab5a97d945fa17489a
  Stored in directory: c:\users\maria\appdata\local\pip\cache\wheels\99\34\23\b19f7de7352af5d1913f2654641432d6740c2666eecf2472ea
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.4

In [41]:
user_features_problems=['user_preference_Boring presentation',
 'user_preference_Graphics',
 'user_preference_Readability',
 'user_preference_Consistency',
 'user_preference_Images',
 'user_preference_Bullets',
 'user_preference_Text size',
 'user_preference_Text heavy',
 'user_preference_Tables',
 'user_preference_Agenda',
 'user_preference_Infographics',
 'user_preference_Positioning',
 'user_preference_Presentation length',
 'user_preference_General tips',
 'user_preference_Presentation skills',
 'user_preference_Powerpoint knowledge',
 'user_preference_tips and tricks',
 'user_preference_Explanation of the problem']

In [42]:
item_features_problems=['Boring presentation',
 'Graphics',
 'Readability',
 'Consistency',
 'Images',
 'Bullets',
 'Text size',
 'Text heavy',
 'Tables',
 'Agenda',
 'Infographics',
 'Positioning',
 'Presentation length',
 'General tips',
 'Presentation skills',
 'Powerpoint knowledge',
 'tips and tricks',
 'Explanation of the problem']

In [46]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from surprise import SVD
from surprise import Dataset, Reader
from surprise.model_selection import train_test_split
from surprise import accuracy

# Content-Based Filtering (CB) using cosine similarity
def content_based_recommender(user_id, top_n=5):
    user_vector = merged_features[user_features_problems].iloc[user_id].values.reshape(1, -1)
    item_vectors = merged_features[item_features_problems].values

    # Calculate cosine similarity without scaling
    similarities = cosine_similarity(user_vector, item_vectors).flatten()
    top_indices = similarities.argsort()[-top_n:][::-1]

    return data1.iloc[top_indices].copy()

# Collaborative Filtering (CF) using Matrix Factorization (SVD)
reader = Reader(rating_scale=(merged_features['rating'].min(), merged_features['rating'].max()))
dataset = Dataset.load_from_df(merged_features[['user_id', 'article_id', 'rating']], reader)
trainset, testset = train_test_split(dataset, test_size=0.2)

model = SVD()
model.fit(trainset)
predictions = model.test(testset)

# Evaluate CF model
rmse = accuracy.rmse(predictions)

# CF Prediction Function
def collaborative_filtering_recommender(user_id, item_id):
    pred = model.predict(user_id, item_id)
    return pred.est

# Generate CB recommendations
cbr = content_based_recommender(user_id=1, top_n=100)

# Create final_score DataFrame
final_score = cbr.copy()

# Add CF score column
final_score["score"] = np.nan

# Loop through each recommended article and get CF scores
for index, row in final_score.iterrows():
    item_id = row["article_id"]
    try:
        score = collaborative_filtering_recommender(user_id=1, item_id=item_id)
        final_score.at[index, "score"] = score
        print(f"CF Score for Item {item_id}: {score:.4f}")
    except Exception as e:
        print(f"Error for item {item_id}: {e}")

# Print final DataFrame
print("\nFinal Score DataFrame:")
print(final_score)

RMSE: 0.3106
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 434: 3.1990
CF Score for Item 299: 4.4301
CF Score for Item 434: 3.1990
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301
CF Score for Item 429: 4.5486
CF Score for Item 299: 4.4301

Final Score DataFrame:
       user_id  article_id  rating           timestamp    location  \
15643       32         299     5.0 2015-04-02 21:00:00    New York
19497       39         429     2.0 2014-06-17 11:00:00     Florida
23681       48         429     2.0 2013-03-20 15:00:00    Illinois
24189       49         429     2.0 2024-02-20 07:00:00     Florida
24851       50         434     2.5 2017-04-27 06:00:00    Illinois
...        ...         ...     ...                 ...         ...
24900       50         299     2.5 2010-11-14 19:00:00    Illinois
3589         8         429     4.0 2010-11-25 19:00:00  California
2623         6         299     2.5 2021-05-30 09:00:00  California
13818       28         429     2.5 2020-08-02 04:00:00     Florida
7038        15         299     4.0 2015-05-09 13:00:00    Illinois

       user_preference_Boring presentation  user_preference_Graphics  \
15643                                    0                         1
19497                                    0                         0
23681                                    0                         0
24189                                    0                         0
24851                                    0                         0
...                                    ...                       ...
24900                                    0                         0
3589                                     0                         0
2623                                     0                         0
13818                                    0                         0
7038                                     0                         0

       user_preference_Readability  user_preference_Consistency  \
15643                            0                            0
19497                            0                            0
23681                            1                            0
24189                            0                            0
24851                            0                            0
...                            ...                          ...
24900                            0                            0
3589                             0                            0
2623                             0                            0
13818                            1                            0
7038                             0                            0

       user_preference_Images  ...  presentation_type_technical_y  \
15643                       0  ...                              0
19497                       1  ...                              0
23681                       0  ...                              0
24189                       0  ...                              0
24851                       0  ...                              0
...                       ...  ...                            ...
24900                       0  ...                              0
3589                        0  ...                              0
2623                        0  ...                              0
13818                       0  ...                              0
7038                        1  ...                              0

       presentation_type_branding_y  audience_type_academic  \
15643                             0                       0
19497                             0                       0
23681                             0                       0
24189                             0                       0
24851                             0                       0
...                             ...                     ...
24900                             0                       0
3589                              0                       0
2623                              0                       0
13818                             0                       0
7038                              0                       0

       audience_type_business  audience_type_kids  audience_type_general  \
15643                       0                   0                      0
19497                       0                   0                      0
23681                       0                   0                      0
24189                       0                   0                      0
24851                       0                   0                      0
...                       ...                 ...                    ...
24900                       0                   0                      0
3589                        0                   0                      0
2623                        0                   0                      0
13818                       0                   0                      0
7038                        0                   0                      0

       audience_type_creative  audience_type_specialized  time_since     score
15643                       0                          0     86733.0  4.430099
19497                       0                          0     93679.0  4.548637
23681                       0                          0    104571.0  4.548637
24189                       0                          0      8843.0  4.548637
24851                       0                          0     68604.0  3.199034
...                       ...                        ...         ...       ...
24900                       0                          0    125135.0  4.430099
3589                        0                          0    124871.0  4.548637
2623                        0                          0     32745.0  4.430099
13818                       0                          0     39974.0  4.548637
7038                        0                          0     85853.0  4.430099

[100 rows x 69 columns]

In [48]:
import time
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from surprise import SVD
from surprise import Dataset, Reader
from surprise.model_selection import train_test_split
from surprise import accuracy

# Start timing
start_time = time.time()

# Content-Based Filtering (CB) using cosine similarity
def content_based_recommender(user_id, top_n=5):
    user_vector = merged_features[user_features_problems].iloc[user_id].values.reshape(1, -1)
    item_vectors = merged_features[item_features_problems].values

    # Calculate cosine similarity without scaling
    similarities = cosine_similarity(user_vector, item_vectors).flatten()
    top_indices = similarities.argsort()[-top_n:][::-1]

    return data1.iloc[top_indices].copy()

# Collaborative Filtering (CF) using Matrix Factorization (SVD)
reader = Reader(rating_scale=(merged_features['rating'].min(), merged_features['rating'].max()))
dataset = Dataset.load_from_df(merged_features[['user_id', 'article_id', 'rating']], reader)
trainset, testset = train_test_split(dataset, test_size=0.2)

model = SVD()
model.fit(trainset)
predictions = model.test(testset)

# Evaluate CF model
rmse = accuracy.rmse(predictions)

# CF Prediction Function
def collaborative_filtering_recommender(user_id, item_id):
    pred = model.predict(user_id, item_id)
    return pred.est

# Generate CB recommendations
cbr = content_based_recommender(user_id=1, top_n=100)

# Create final_score DataFrame
final_score = cbr.copy()

# Add CF score column
final_score["score"] = np.nan

# Loop through each recommended article and get CF scores
for index, row in final_score.iterrows():
    item_id = row["article_id"]
    try:
        score = collaborative_filtering_recommender(user_id=1, item_id=item_id)
        final_score.at[index, "score"] = score
        print(f"CF Score for Item {item_id}: {score:.4f}")
    except Exception as e:
        print(f"Error for item {item_id}: {e}")

# End timing
end_time = time.time()
execution_time = end_time - start_time

# Print final DataFrame
print("\nFinal Score DataFrame:")
print(final_score)

# Print execution time
print(f"\nTotal Execution Time: {execution_time:.2f} seconds")

RMSE: 0.3145
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 434: 3.2097
CF Score for Item 299: 4.5008
CF Score for Item 434: 3.2097
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008
CF Score for Item 429: 4.3998
CF Score for Item 299: 4.5008

Final Score DataFrame:
       user_id  article_id  rating           timestamp    location  \
15643       32         299     5.0 2015-04-02 21:00:00    New York
19497       39         429     2.0 2014-06-17 11:00:00     Florida
23681       48         429     2.0 2013-03-20 15:00:00    Illinois
24189       49         429     2.0 2024-02-20 07:00:00     Florida
24851       50         434     2.5 2017-04-27 06:00:00    Illinois
...        ...         ...     ...                 ...         ...
24900       50         299     2.5 2010-11-14 19:00:00    Illinois
3589         8         429     4.0 2010-11-25 19:00:00  California
2623         6         299     2.5 2021-05-30 09:00:00  California
13818       28         429     2.5 2020-08-02 04:00:00     Florida
7038        15         299     4.0 2015-05-09 13:00:00    Illinois

       user_preference_Boring presentation  user_preference_Graphics  \
15643                                    0                         1
19497                                    0                         0
23681                                    0                         0
24189                                    0                         0
24851                                    0                         0
...                                    ...                       ...
24900                                    0                         0
3589                                     0                         0
2623                                     0                         0
13818                                    0                         0
7038                                     0                         0

       user_preference_Readability  user_preference_Consistency  \
15643                            0                            0
19497                            0                            0
23681                            1                            0
24189                            0                            0
24851                            0                            0
...                            ...                          ...
24900                            0                            0
3589                             0                            0
2623                             0                            0
13818                            1                            0
7038                             0                            0

       user_preference_Images  ...  presentation_type_technical_y  \
15643                       0  ...                              0
19497                       1  ...                              0
23681                       0  ...                              0
24189                       0  ...                              0
24851                       0  ...                              0
...                       ...  ...                            ...
24900                       0  ...                              0
3589                        0  ...                              0
2623                        0  ...                              0
13818                       0  ...                              0
7038                        1  ...                              0

       presentation_type_branding_y  audience_type_academic  \
15643                             0                       0
19497                             0                       0
23681                             0                       0
24189                             0                       0
24851                             0                       0
...                             ...                     ...
24900                             0                       0
3589                              0                       0
2623                              0                       0
13818                             0                       0
7038                              0                       0

       audience_type_business  audience_type_kids  audience_type_general  \
15643                       0                   0                      0
19497                       0                   0                      0
23681                       0                   0                      0
24189                       0                   0                      0
24851                       0                   0                      0
...                       ...                 ...                    ...
24900                       0                   0                      0
3589                        0                   0                      0
2623                        0                   0                      0
13818                       0                   0                      0
7038                        0                   0                      0

       audience_type_creative  audience_type_specialized  time_since     score
15643                       0                          0     86733.0  4.500834
19497                       0                          0     93679.0  4.399772
23681                       0                          0    104571.0  4.399772
24189                       0                          0      8843.0  4.399772
24851                       0                          0     68604.0  3.209697
...                       ...                        ...         ...       ...
24900                       0                          0    125135.0  4.500834
3589                        0                          0    124871.0  4.399772
2623                        0                          0     32745.0  4.500834
13818                       0                          0     39974.0  4.399772
7038                        0                          0     85853.0  4.500834

[100 rows x 69 columns]

Total Execution Time: 0.29 seconds

In [47]:
import numpy as np

def evaluate_predictions(y_pred, y_test):
    """
    Evaluates predictions using Mean Absolute Error (MAE), 
    Mean Squared Error (MSE), and Root Mean Squared Error (RMSE).

    Parameters:
    - y_pred: Predicted values (numpy array or list).
    - y_test: True target values (numpy array or list).

    Returns:
    - mae: Mean Absolute Error
    - mse: Mean Squared Error
    - rmse: Root Mean Squared Error
    """
    # Ensure arrays are flattened for consistency
    y_pred = np.array(y_pred).flatten()
    y_test = np.array(y_test).flatten()

    # Calculate error metrics
    differences = y_pred - y_test
    absolute_differences = np.abs(differences)
    
    mae = np.mean(absolute_differences)
    mse = np.mean(differences ** 2)
    rmse = np.sqrt(mse)

    # Print results
    print("Mean Absolute Error (MAE):", mae)
    print("Mean Squared Error (MSE):", mse)
    print("Root Mean Squared Error (RMSE):", rmse)

    return mae, mse, rmse
    
evaluate_predictions(final_score['score'], final_score['rating'])

Mean Absolute Error (MAE): 1.1330841008971246
Mean Squared Error (MSE): 1.9636864624590238
Root Mean Squared Error (RMSE): 1.401315975238641

(1.1330841008971246, 1.9636864624590238, 1.401315975238641)

In [245]:
temp_df = data1[data1['user_id'] == user_id]
temp_df.columns

Index(['user_id', 'article_id', 'rating', 'timestamp', 'location',
       'user_preference_Boring presentation', 'user_preference_Graphics',
       'user_preference_Readability', 'user_preference_Consistency',
       'user_preference_Images', 'user_preference_Bullets',
       'user_preference_Text size', 'user_preference_Text heavy',
       'user_preference_Tables', 'user_preference_Agenda',
       'user_preference_Infographics', 'user_preference_Positioning',
       'user_preference_Presentation length', 'user_preference_General tips',
       'user_preference_Presentation skills',
       'user_preference_Powerpoint knowledge',
       'user_preference_tips and tricks',
       'user_preference_Explanation of the problem', 'user_type_business',
       'user_type_teacher', 'user_type_student', 'user_type_researcher',
       'user_type_manager', 'user_type_technical', 'user_type_specialist',
       'presentation_type_formal_x', 'presentation_type_creative_x',
       'presentation_type_students_x', 'presentation_type_technical_x',
       'presentation_type_branding_x', 'Boring presentation', 'Graphics',
       'Readability', 'Consistency', 'Images', 'Bullets', 'Text size',
       'Text heavy', 'Tables', 'Agenda', 'Infographics', 'Positioning',
       'Presentation length', 'General tips', 'Presentation skills',
       'Powerpoint knowledge', 'tips and tricks', 'Explanation of the problem',
       'location_restrictions', 'Main issue', 'presentation_type_formal_y',
       'presentation_type_creative_y', 'presentation_type_students_y',
       'presentation_type_technical_y', 'presentation_type_branding_y',
       'audience_type_academic', 'audience_type_business',
       'audience_type_kids', 'audience_type_general', 'audience_type_creative',
       'audience_type_specialized', 'time_since'],
      dtype='object')

In [246]:
user_features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [255]:
import numpy as np

# --- Select the user with id 1 ---
# (Here we assume that user id 1 corresponds to index 1 in our arrays; adjust if needed.)
user_id = 1
######### only before prediction is the filtering-the training of model is on full datat
temp_df = data1[
    (data1['user_id'] == user_id) &
    (data1['location'] != data1['location_restrictions'])].copy()
user_features_df = temp_df[user_features]
item_features_df = temp_df[item_features]
time_features_df = extract_time_features(temp_df['timestamp'], start_time)
problem_seq_df = problem_sequences_df[problem_sequences_df['user_id'] == user_id]

problem_sequences_features = []
user_data = {}
for i in range(len(user_features_df)):
    _, weighted_problems = calculate_problem_weights(df_user, "Time_since_first_submission_hours", problem_features, days_window=180, decay_factor=0.01, apply_filter=False)
    problem_sequences_features.append(weighted_problems)

problem_seq_val = np.array(problem_sequences_features)

y_pred_val = best_model.predict([user_features_df, item_features_df, time_features_df, problem_seq_val])
temp_df['pred'] = y_pred_val

In [259]:
temp_df.columns

Index(['user_id', 'article_id', 'rating', 'timestamp', 'location',
       'user_preference_Boring presentation', 'user_preference_Graphics',
       'user_preference_Readability', 'user_preference_Consistency',
       'user_preference_Images', 'user_preference_Bullets',
       'user_preference_Text size', 'user_preference_Text heavy',
       'user_preference_Tables', 'user_preference_Agenda',
       'user_preference_Infographics', 'user_preference_Positioning',
       'user_preference_Presentation length', 'user_preference_General tips',
       'user_preference_Presentation skills',
       'user_preference_Powerpoint knowledge',
       'user_preference_tips and tricks',
       'user_preference_Explanation of the problem', 'user_type_business',
       'user_type_teacher', 'user_type_student', 'user_type_researcher',
       'user_type_manager', 'user_type_technical', 'user_type_specialist',
       'presentation_type_formal_x', 'presentation_type_creative_x',
       'presentation_type_students_x', 'presentation_type_technical_x',
       'presentation_type_branding_x', 'Boring presentation', 'Graphics',
       'Readability', 'Consistency', 'Images', 'Bullets', 'Text size',
       'Text heavy', 'Tables', 'Agenda', 'Infographics', 'Positioning',
       'Presentation length', 'General tips', 'Presentation skills',
       'Powerpoint knowledge', 'tips and tricks', 'Explanation of the problem',
       'location_restrictions', 'Main issue', 'presentation_type_formal_y',
       'presentation_type_creative_y', 'presentation_type_students_y',
       'presentation_type_technical_y', 'presentation_type_branding_y',
       'audience_type_academic', 'audience_type_business',
       'audience_type_kids', 'audience_type_general', 'audience_type_creative',
       'audience_type_specialized', 'time_since', 'pred'],
      dtype='object')

In [306]:
import pandas as pd

def extract_user_profile(temp_df: pd.DataFrame):
    # Define columns to extract
    columns_to_extract = [
        'user_id', 'article_id', 'pred',
        'presentation_type_formal_x', 'presentation_type_creative_x', 'presentation_type_students_x',
        'presentation_type_technical_x', 'presentation_type_branding_x',
        'audience_type_academic', 'audience_type_business',
        'audience_type_general', 'audience_type_specialized',
        'time_since'
    ]
    
    # Extract relevant data
    extracted_df = temp_df[columns_to_extract]
    
    # Extract a sample user profile (first user in dataframe)
    first_user = extracted_df.iloc[0]
    
    # Identify the preferred presentation type
    preferred_presentation_type = next(
        (col.replace('presentation_type_', '').replace('_x', '') 
         for col in columns_to_extract[3:8] if first_user[col] == 1),
        None
    )
    
    # Identify the preferred audience type
    preferred_audience_type = next(
        (col.replace('audience_type_', '') 
         for col in columns_to_extract[8:12] if first_user[col] == 1),
        None
    )
    
    # Construct user profile dictionary
    user_profile = {
        'user_id': int(first_user['user_id']),
        'preferred_presentation_type': preferred_presentation_type,
        'audience_type': preferred_audience_type
    }
    
    return extracted_df, user_profile

# Example usage:
extracted_df, user_profile = extract_user_profile(temp_df)
# print(extracted_df.head())
# print(user_profile)

def extract_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Extracts specific columns from the given DataFrame.
    
    Parameters:
        df (pd.DataFrame): The input DataFrame.
    
    Returns:
        pd.DataFrame: A new DataFrame containing only the specified columns.
    """
    columns_to_extract = [
        'user_id',
        'article_id',
        'rating',
        'pred',
        'Boring presentation',
         'Graphics',
         'Readability',
         'Consistency',
         'Images',
         'Bullets',
         'Text size',
         'Text heavy',
         'Tables',
         'Agenda',
         'Infographics',
         'Positioning',
         'Presentation length',
         'General tips',
         'Presentation skills',
         'Powerpoint knowledge',
         'tips and tricks',
         'Explanation of the problem',
         'presentation_type_formal_y',
         'presentation_type_creative_y',
         'presentation_type_students_y',
         'presentation_type_technical_y',
         'presentation_type_branding_y',
         'audience_type_academic',
         'audience_type_business',
         'audience_type_kids',
         'audience_type_general',
         'audience_type_creative',
         'audience_type_specialized',
        'time_since'
    ]

    return df[columns_to_extract]

extracted_df = extract_columns(temp_df)

In [321]:
import numpy as np
import pandas as pd

#add Long-Tail Boosting: introduces a weighting mechanism to prioritize less popular items, encouraging their recommendation.

def sort_by_preferred_presentation(recommendations, user_profile):
    """
    Sort recommendations by the user's preferred presentation type.

    Parameters:
      - recommendations (pd.DataFrame): DataFrame containing presentation types.
      - user_profile (dict): Dictionary containing user preferences.
      
    Returns:
      - pd.DataFrame: Sorted recommendations.
    """
    preferred_type = user_profile.get('preferred_presentation_type')
    if preferred_type in recommendations.columns:
        recommendations['is_preferred'] = recommendations[preferred_type] == 1
        recommendations = recommendations.sort_values(by='is_preferred', ascending=False).drop(columns='is_preferred')
    return recommendations

def limit_recommendations_by_engagement_time(recommendations, engagement_time):
    """
    Limit the number of recommendations based on the user's engagement time.

    Parameters:
      - recommendations (pd.DataFrame): DataFrame of sorted recommendations.
      - engagement_time (float): User engagement time in minutes.
    
    Returns:
      - pd.DataFrame: Limited recommendations.
    """
    max_recs = int(engagement_time / 2)  # Assume 5 minutes per article ,but give more choice
    return recommendations.head(max_recs)

def audience_type_decay(row, user_profile):
    """
    Adjust scores based on audience type match.

    Parameters:
      - row (pd.Series): A row from the recommendations DataFrame.
      - user_profile (dict): Dictionary with user preferences.
    
    Returns:
      - float: Adjusted score.
    """
    score = row.get('pred', 0)
    audience_type = user_profile.get('audience_type')  # Extract audience type

    if audience_type:  # Only proceed if audience_type is not None
        audience_columns = [col for col in row.index if col.startswith('audience_type_')]
        
        for col in audience_columns:
            if audience_type in col and row.get(col, 0) == 1:
                score *= 1.1  # Boost if the audience type matches

    return score


def finalize_recommendations(predicted_articles, user_profile, engagement_time):
    """
    Finalize recommendations by sorting, applying audience type boost,
    removing duplicates, and limiting based on engagement time.

    Parameters:
      - predicted_articles (pd.DataFrame): Data with relevant columns.
      - user_profile (dict): Dictionary with user preferences.
      - engagement_time (float): User's engagement time in minutes.
    
    Returns:
      - pd.DataFrame: Processed recommendations.
    """
    # Sort by preferred presentation type
    recs_sorted = sort_by_preferred_presentation(predicted_articles.copy(), user_profile)

    # Adjust scores using audience type decay
    recs_sorted['utility_score'] = recs_sorted.apply(
        lambda row: audience_type_decay(row, user_profile), axis=1
    )

    # Sort recommendations by adjusted score
    recs_sorted = recs_sorted.sort_values('utility_score', ascending=False)

    # Remove duplicates based on 'article_id'
    recs_sorted = recs_sorted.drop_duplicates(subset='article_id', keep='first')

    # Limit recommendations based on engagement time
    final_recs = limit_recommendations_by_engagement_time(recs_sorted, engagement_time)

    return final_recs

# ------------------------------------------------------------------------------
# Example Usage:
# ------------------------------------------------------------------------------

# Create a sample DataFrame matching the provided dataset structure
predicted_articles = extract_columns(temp_df)

# Define a sample user profile with preferences
extracted_df, user_profile = extract_user_profile(temp_df)

# Define the user's engagement time
engagement_time = 30  # 30 minutes

# Get final recommendations
final_recommendations = finalize_recommendations(predicted_articles, user_profile, engagement_time)

print("Final Recommendations (Top Items):")
print(final_recommendations[['article_id','pred','rating','time_since', 'utility_score']].head(10))

###add one article from the new once that is most similar to recommended once

Final Recommendations (Top Items):
      article_id      pred  rating  time_since  utility_score
650           14  5.276542     5.0    159917.0       5.276542
100            3  5.257366     5.0      3978.0       5.257366
200            5  5.253772     5.0     76184.0       5.253772
8450         170  5.253342     5.0     60789.0       5.253342
2100          43  5.199001     5.0     75838.0       5.199001
1050          22  5.182315     5.0     82668.0       5.182315
7550         152  5.172397     5.0    148895.0       5.172397
6250         126  5.166687     5.0     31139.0       5.166687
1200          25  5.161759     5.0     18613.0       5.161759
8900         179  5.148324     5.0    156817.0       5.148324

In [322]:
temp_po = temp_df.copy()

temp_po=temp_po.sort_values('pred', ascending=False)

In [323]:
 temp_po[['article_id','pred','rating','time_since']].head(10)

      article_id      pred  rating  time_since
650           14  5.276542     5.0    159917.0
100            3  5.257366     5.0      3978.0
200            5  5.253772     5.0     76184.0
8450         170  5.253342     5.0     60789.0
2100          43  5.199001     5.0     75838.0
1050          22  5.182315     5.0     82668.0
7550         152  5.172397     5.0    148895.0
6250         126  5.166687     5.0     31139.0
1200          25  5.161759     5.0     18613.0
8900         179  5.148324     5.0    156817.0

In [324]:
############################### Step 6 evaluate the RS

In [325]:
import pandas as pd

def calculate_precision(df, true_rating_col, predicted_rating_col, relevance_threshold):
    """
    Calculate precision based on the formula:
    Precision = Total Recommendations / Number of Relevant Recommendations.

    Parameters:
        df (pd.DataFrame): The dataset containing true and predicted ratings.
        true_rating_col (str): Column name for true ratings.
        predicted_rating_col (str): Column name for predicted ratings.
        relevance_threshold (float): threshold to determine relevance.

    Returns:
        float: Precision value.
    """
    print("Relevance treshold "+ str(relevance_threshold))
    # Determine relevant items based on true ratings
    df['is_relevant'] = df[true_rating_col] >= relevance_threshold

    # Determine predicted relevant items based on predicted ratings
    df['predicted_relevant'] = df[predicted_rating_col] >= relevance_threshold

    # Calculate Total Recommendations (predicted relevant items)
    total_recommendations = df['predicted_relevant'].sum()

    # Calculate Number of Relevant Recommendations (actual relevant items)
    number_of_relevant_recommendations = df['is_relevant'].sum()

    # Calculate Precision
    precision = (total_recommendations / number_of_relevant_recommendations
                 if number_of_relevant_recommendations > 0 else 0)

    return precision

# Calculate precision
# Define relevance threshold: Top 20% threshold
relevance_threshold = ratings_matrix['rating'].quantile(0.90)
precision = calculate_precision(temp_po,'rating', 'pred',relevance_threshold)
print(f"Precision: {precision}")

Relevance treshold 4.5
Precision: 0.9560439560439561

In [326]:
Novelty measures how surprising or unexpected a recommendation is to the user. It’s often calculated using item popularity (less popular = more novel).

Steps:

Assign a popularity score to each item (e.g., based on how often it appears in the dataset). Compute the novelty as the inverse popularity for each recommendation and average across recommendations.

SyntaxError: invalid syntax (3433406256.py, line 1)

In [327]:
import pandas as pd

def compute_novelty(data1: pd.DataFrame, final_recommendations: pd.DataFrame) -> float:
    """
    Computes the novelty of the recommended articles.

    Parameters:
        data1 (pd.DataFrame): DataFrame containing all articles.
        final_recommendations (pd.DataFrame): DataFrame containing recommended articles.
    
    Returns:
        float: The average novelty score of recommended articles.
    """
    # Step 1: Compute article popularity in data1
    article_counts = data1['article_id'].value_counts(normalize=True)  # Normalized popularity
    print(article_counts)
    # Step 2: Compute novelty scores (inverse of popularity)
    novelty_scores = 1 - article_counts
    
    # Step 3: Get novelty of recommended articles
    final_recommendations['novelty_score'] = final_recommendations['article_id'].map(novelty_scores).fillna(1)  # Unseen articles get max novelty
    
    # Step 4: Compute average novelty
    avg_novelty = final_recommendations['novelty_score'].mean()

    return avg_novelty

# Example usage
novelty_score = compute_novelty(data1, final_recommendations)
print(f"Average Novelty Score: {novelty_score:.4f}")

1      0.002
330    0.002
343    0.002
342    0.002
341    0.002
       ...
162    0.002
161    0.002
160    0.002
159    0.002
500    0.002
Name: article_id, Length: 500, dtype: float64
Average Novelty Score: 0.9980

In [328]:
Diversity measures how different the recommended items are from each other. It’s typically calculated using pairwise similarity between items in the recommendations.

Steps:

Calculate pairwise similarity for the features column. Compute the average dissimilarity (1 - similarity) for all pairs of recommendations.

SyntaxError: invalid syntax (1049687216.py, line 1)

In [329]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def calculate_diversity(recommended_items, item_features, item_id_col="article_id"):
    """
    Calculates diversity of recommendations based on item feature similarity.

    Args:
        recommended_items (DataFrame): DataFrame containing recommended items.
        item_features (list): List of column names representing item features.
        item_id_col (str): Column name in `final_rec` and `tada1` representing item IDs.

    Returns:
        float: Diversity score (higher means more diverse recommendations).
    """

    # Ensure we have enough items to calculate diversity
    if recommended_items.shape[0] < 2:
        return 1.0  # Maximum diversity if only one or zero items are recommended

    # Compute pairwise cosine similarity
    similarity_matrix = cosine_similarity(recommended_items[['Boring presentation',
         'Graphics',
         'Readability',
         'Consistency',
         'Images',
         'Bullets',
         'Text size',
         'Text heavy',
         'Tables',
         'Agenda',
         'Infographics',
         'Positioning',
         'Presentation length',
         'General tips',
         'Presentation skills',
         'Powerpoint knowledge',
         'tips and tricks',
         'Explanation of the problem']])

    # Get upper triangle values (excluding diagonal)
    sim_values = similarity_matrix[np.triu_indices(len(recommended_items), k=1)]

    # Calculate diversity (1 - mean similarity)
    diversity_score = 1 - np.mean(sim_values) if len(sim_values) > 0 else 1.0
    
    return round(diversity_score,2)


calculate_diversity(final_recommendations, item_features)

0.52

In [330]:
Types of Coverage:
User Coverage:

The percentage of users for whom the system can provide recommendations.
If coverage = 1, it means the system has made recommendations for 100% of the users.
Formula:

User Coverage
=
Users with Recommendations
Total Users
User Coverage=
Total Users
Users with Recommendations
​

Item Coverage:

The percentage of items that appear in at least one recommendation list.
If coverage = 1, it means every item in the catalog has been recommended at least once.
Formula:

Item Coverage
=
Items in Recommendations
Total Items
Item Coverage=
Total Items
Items in Recommendations
​

Example Interpretation:
User Coverage = 1:
The system is able to generate recommendations for all users in the dataset.
Item Coverage = 1:
The system has recommended all items from the catalog to at least one user.
Why Is Coverage Important?
Coverage is critical in recommendation systems for the following reasons:

Inclusivity: Ensures that all users or items are considered, preventing bias.
Diversity: Higher item coverage generally correlates with more diverse recommendations.

SyntaxError: invalid syntax (3360879187.py, line 1)

In [331]:
final_recommendations

,user_id,article_id,rating,pred,Boring presentation,Graphics,Readability,Consistency,Images,Bullets,...,presentation_type_branding_y,audience_type_academic,audience_type_business,audience_type_kids,audience_type_general,audience_type_creative,audience_type_specialized,time_since,utility_score,novelty_score
650,1,14,5.0,5.276542,0,1,1,0,0,0,...,0,0,0,0,0,0,0,159917.0,5.276542,0.998
100,1,3,5.0,5.257366,1,0,0,0,1,1,...,0,0,0,0,0,0,0,3978.0,5.257366,0.998
200,1,5,5.0,5.253772,0,1,0,0,1,1,...,0,0,0,0,0,0,0,76184.0,5.253772,0.998
8450,1,170,5.0,5.253342,0,1,0,0,0,1,...,0,0,0,0,0,0,0,60789.0,5.253342,0.998
2100,1,43,5.0,5.199001,0,1,0,1,1,0,...,0,0,0,0,0,0,0,75838.0,5.199001,0.998
1050,1,22,5.0,5.182315,1,1,1,0,1,1,...,0,0,0,0,0,0,0,82668.0,5.182315,0.998
7550,1,152,5.0,5.172397,1,0,0,1,1,0,...,0,0,0,0,0,0,0,148895.0,5.172397,0.998
6250,1,126,5.0,5.166687,0,0,1,1,1,1,...,0,0,0,0,0,0,0,31139.0,5.166687,0.998
1200,1,25,5.0,5.161759,1,1,1,0,1,1,...,0,0,0,0,0,0,0,18613.0,5.161759,0.998
8900,1,179,5.0,5.148324,0,0,1,0,1,1,...,0,0,0,0,0,0,0,156817.0,5.148324,0.998
10550,1,212,5.0,5.140253,0,0,1,0,1,1,...,0,0,0,0,0,0,0,86199.0,5.140253,0.998
13700,1,275,5.0,5.136290,0,1,1,1,1,1,...,0,0,0,0,0,0,0,1516.0,5.136290,0.998
300,1,7,5.0,5.135853,0,0,0,1,0,0,...,0,0,0,0,0,0,0,161847.0,5.135853,0.998
12450,1,250,5.0,5.128272,1,0,0,0,1,0,...,0,0,0,0,0,0,0,167570.0,5.128272,0.998
13100,1,263,5.0,5.110623,0,0,1,1,1,0,...,0,0,0,0,0,0,0,105923.0,5.110623,0.998

In [332]:
# Ensure total_items is properly assigned
total_items = data1['article_id'].nunique()  # Count unique articles in the full dataset
print(total_items)  # Should print the correct number of unique articles
#500
# Count unique articles in recommendations
items_in_recommendations = final_recommendations['article_id'].nunique()
print(items_in_recommendations)  # Should print the correct number of unique articles in recommendations

# Compute item coverage
item_coverage = items_in_recommendations / total_items

# Print correct item coverage
print(f"Item Coverage: {item_coverage:.4f}")  # Corrected print statement

500
15
Item Coverage: 0.0300

In [ ]:
####retrying